//  DATABASE CONNECTION CONFIGURATION
exports.MS_SQL_USER = process.env.ENV_MS_SQL_USER;
exports.MS_SQL_PASSWORD = process.env.ENV_MS_SQL_PASSWORD;
exports.MS_SQL_SERVER = process.env.ENV_MS_SQL_SERVER;
exports.MS_SQL_PORT = process.env.ENV_MS_SQL_PORT;
exports.MS_SQL_DATABASE = process.env.ENV_MS_SQL_DATABASE;

// DATABASE NAMES
exports.HEALTH_ID_DATABASE = process.env.ENV_HEALTH_ID_DATABASE;
// DATABASE TABLE NAMES
exports.DBO_HEALTH_ID_TABLE = process.env.ENV_DBO_HEALTH_ID_TABLE;
// HEALTH ID DATABASE COLUMN NAMES
exports.PROVINCE_HEALTH_COLUMN = process.env.ENV_PROVINCE_HEALTH_COLUMN;
exports.SERVICE_AREA_HEALTH_COLUMN = process.env.ENV_SERVICE_AREA_HEALTH_COLUMN;
exports.DISTRICT_HEALTH_COLUMN = process.env.ENV_DISTRICT_HEALTH_COLUMN;
exports.SUBDISTRICT_HEALTH_COLUMN = process.env.ENV_SUB_DISTRICT_HEALTH_COLUMN;
